name: CI run on PR
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-rpms:
    name: build for ${{ matrix.distro }} on ${{ matrix.arch }}
    runs-on: ubuntu-latest
    env:
      BASEIMAGE: ${{ matrix.distro }}
      WALGVERSION: v3.0.4b
      WALGURL: https://github.com/mannemsolutions/wal-g.git
      COMPOSE_DOCKER_CLI_BUILD: 1
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
        distro:
          #- rockylinux:8
          - rockylinux:9
          - fedora:39
          #- fedora:40
          #- fedora:41
          #- fedora:42
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: git module stuff
        run: |
          git clone ${{ env.WALGURL }} wal-g
          cd wal-g
          git checkout ${{ env.WALGVERSION }}
          git show --stat | head -n3
      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: compose
        run: |
          docker-compose up builder
          find rpms
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_BUILDKIT: 1
