name: Build release
on:
  release:
    types:
      - published

env:
  WALGVERSION: ${{ github.ref_name }}
  WALGURL: https://github.com/mannemsolutions/wal-g.git
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build-rpms:
    name: build for ${{ matrix.distro }} on ${{ matrix.arch }}
    runs-on: ubuntu-latest
    env:
      BASEIMAGE: ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
        distro:
          - rockylinux:8
          - rockylinux:9
          - fedora:39
          - fedora:40
          - fedora:41
          - fedora:42
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: git module stuff
        run: |
          git clone $WALGURL wal-g
          cd wal-g
          git checkout $WALGVERSION
          git show --stat | head -n3
      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: compose
        run: |
          docker-compose up builder
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_BUILDKIT: 1
      - name: Add rpm to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rpms/*

  build_and_push_image:
    name: Push image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: git module stuff
        run: |
          git clone $WALGURL wal-g
          cd wal-g
          git checkout $WALGVERSION
          git show --stat | head -n3

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository }},enable=true
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest
            type=sha

      - name: Build and push operator image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/wal-g-pg/Dockerfile
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ github.ref_name }}
